proxy:
  host: localhost
  port: 4040

target:
  probability: 50
  target_host: http://localhost:8000
  default_host: http://localhost:8000

https:
  enabled: false
  cert_path: ""
  key_path: ""

allowed_verbs:
  - GET
  - DELETE